name: Home server deployment
on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        required: true
        type: string
      DEPLOY_PATH:
        required: true
        type: string
      POSTDEPLOY_SCRIPT_PATH:
        required: false
        type: string
    secrets:
      PRIVATE_KEY:
        required: true
      SERVER_FINGERPRINT:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{inputs.ARTIFACT_NAME}}
        path: /tmp/dist
    - name: setup SSH key and known_hosts
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{secrets.SERVER_FINGERPRINT}}" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
    - name: deploy package
      run: |
        ( cd /tmp/dist && zip -r ~/package.zip . ; cd - )
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} Remove-Item -path ${{inputs.DEPLOY_PATH}} -recurse
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} mkdir ${{inputs.DEPLOY_PATH}} 
        scp /tmp/dist/package.zip ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{inputs.DEPLOY_PATH}}/package.zip
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} tar -xf ${{inputs.DEPLOY_PATH}}/package.zip -C ${{inputs.DEPLOY_PATH}}
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} rm ${{inputs.DEPLOY_PATH}}/package.zip
    - name: run postdeploy script
      if: inputs.POSTDEPLOY_SCRIPT_PATH != ''
      run: |
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} 'bash -s' < ${{inputs.POSTDEPLOY_SCRIPT_PATH}}
    - name: clean up
      if: always()
      run: |
        rm -rf ~/.ssh
        rm -rf /tmp/dist
